ALTER TABLE `Category` ADD COLUMN `image` LONGTEXT NULL;

ALTER TABLE `Product`
  ADD COLUMN `isBestSeller` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `isRecommended` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `isPopular` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `showOnHomepage` BOOLEAN NOT NULL DEFAULT true;
